export PATH := /opt/gcc-4.8.1/bin:$(PATH)

# generate config file
$(shell ./build_deps.sh build_config.mk)
# this file is generated by the previous line to set build flags
include build_config.mk

export CGO_CFLAGS=-g -O2 -DNDEBUG -I$(ROCKSDB)/include
export CGO_LDFLAGS=-L$(ROCKSDB) -lrocksdb $(PLATFORM_LDFLAGS)

GO_FLAGS  = --ldflags '-extldflags "-static-libstdc++"'
#GO_FLAGS = --ldflags '-extldflags "-static-libstdc++ -static-libgcc"'
#GO_FLAGS = -v -x --ldflags '-extldflags "-static"'

all: build

build: rocksdb-lib go-deps
	go install $(GO_FLAGS) ./...

get: rocksdb-lib go-deps
	go get ./...
	
test: rocksdb-lib go-deps
	go test -v ./...

clean: rocksdb-clean
	go clean -i ./...
	rm build_config.mk

rocksdb-clean:
	rm -rf $(ROCKSDB)

rocksdb-lib:
	if [ ! -f "$(ROCKSDB)/librocksdb.a" ]; then \
		./build_deps.sh -dl; \
		make -C $(ROCKSDB) static_lib; \
	fi

go-deps:
	go get github.com/BurntSushi/toml
	go get github.com/GeertJohan/go.linenoise
