export PATH := /opt/gcc-4.8.1/bin:$(PATH)

# generate config file
$(shell ./build_deps.sh build_config.mk)
# this file is generated by the previous line to set build flags
include build_config.mk

all: rocksdb-lib go-deps
	go install --ldflags '-extldflags "-static-libstdc++"' ./...

get: rocksdb-lib go-deps
	go get ./...

test: rocksdb-lib go-deps
	go test -v ./...

clean: rocksdb-clean
	go clean -i ./...
	rm build_config.mk

rocksdb-clean:
	rm -rf $(ROCKSDB)

rocksdb-lib:
	./build_deps.sh -build_rocksdb

go-deps:
	go get github.com/BurntSushi/toml
	go get github.com/GeertJohan/go.linenoise
